# Generated by Django 2.0.5 on 2018-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
