# Generated by Django 2.0.5 on 2018-05-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testForm', '0002_formdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDat',
        ),
    ]
